apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  selector:
    matchLabels:
      app: order-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: order-pod
    spec:
      containers:
        - name: order-container
          image: bollygame94/microserv-assign:orders-api
          ports:
            - containerPort: 80
