apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    name: order
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: order-pod
